---
cog_bundle_version: 3
name: pipewrench
description: "Miscellaneous Cog pipeline utilities"
version: "0.2.0"
docker:
  image: cogcmd/pipewrench
  tag: "0.2.0"
commands:
  for:
    executable: /home/bundle/cog-command
    description: "Generator function for pipeline inputs"
    documentation: "pipewrench:for name in <arg1> ... <argN> - generate a list of objects with the value of arg1..N as the value of the field with the given name"
    rules: [ 'allow' ]
  dump:
    executable: /home/bundle/cog-command
    description: "Return Cog pipeline options and input"
    documentation: |
      debug:dump [--env | -e] [--input | -i]

      Options:
        --env     Only return environment variables
        --input   Only return STDIN content
    options:
      env:
        type: bool
        required: false
        short_flag: e
      input:
        type: bool
        required: false
        short_flag: i
    rules: [ 'allow' ]
templates:
  preformatted:
    slack: '>>> ```{{{ body }}}```'
    hipchat: '<pre>{{{ body }}}</pre>'
